version: '3.9'

services:
  bridge-postgres:
    image: postgres:16
    container_name: bridge-postgres
    restart: always
    environment:
      POSTGRES_DB: bridgebank
      POSTGRES_USER: bridge
      POSTGRES_PASSWORD: bridge123
    ports:
      - "5432:5432"
    volumes:
      - bridge_postgres_data:/var/lib/postgresql/data

volumes:
  bridge_postgres_data: